let handler = async (m, { conn, usedPrefix }) => {
  await conn.sendButton(m.chat, `“${pickRandom(global.bucin)}”`, author, 'quote', `${usedPrefix}quote`, m)
}
handler.help = ['quote']
handler.tags = ['fun']
handler.command = /^(quote)$/i
handler.owner = false
handler.mods = false
handler.premium = false
handler.group = false
handler.private = false

handler.admin = false
handler.botAdmin = false

handler.fail = null

module.exports = handler

function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())]
}


// https://jalantikus.com/tips/kata-kata-bucin/
global.bucin = [
   "Mən tək qalmağı seçirəm, çünki mükəmməl olanı gözlədiyim üçün deyil, heç vaxt təslim olmayan birinə ehtiyacım var."  ,
  “Tək insan hələ tapmadığı ortaqla yaradılmışdır”.  ,
  "Subaylar. Bəlkə də Tanrının "Yanlış sevgidən dincəl" deməsi belədir."  ,
  "Subaylar, sonradan daha səviyyəli bir sevgi üçün şəxsi inkişaflarına üstünlük verən gənclərdir."  ,
  "Mən mükəmməl olan birini deyil, güclü tərəflərimə görə mükəmməl olan birini axtarıram."  ,
  "İnsanların sevgililəri bizim gözləyən can yoldaşlarımızdır."  ,
  "Subaylar keçməlidir. Hər şeyin bir vaxtı var, bütün tənhalığın halal aşiqi ilə birlik olur. Səbirli olun."  ,
  "Romeo Cülyetta üçün ölərdi, Cek Rozu xilas etmək üçün öldü. Nəticə odur ki, yaşamaq istəyirsənsə, subay ol."  ,
  "Mən insanları güclü tərəflərinə görə deyil, səmimiyyətlərinə görə axtarıram."  ,
  "Madmates tez-tez qarışdırılan flip-floplar deyil. Ona görə də düzgün mübarizə aparmağa davam edin."  ,
  "Əgər sən gitara ifaçısısansa, mən gitaraçı olmaq istəmirəm. Çünki səni atmaq istəmirəm."  ,
  "Əgər səni sevmək bir illüziyadırsa, qoy əbədi olaraq təsəvvür edim."  ,
  – Canım... Mənim işim ancaq səni sevməkdir, taleylə mübarizə aparmaq yox.  ,
  "Səninlə olanda 1 saat sadəcə 1 saniyə kimi hiss olunur, amma səndən uzaq olanda 1 gün 1 il olur."  ,
  "Kolak bananları sumedanq bilir, məsafə uzansa da sevgim heç vaxt itməz."  ,
  "Mən tək olmaq istəyirəm, tək deyil."  ,
  "Yaxşı olacağıma söz verə bilmərəm. Amma söz verirəm ki, həmişə sənin yanında olacağam."  ,
  "Xalq nümayəndəsi olsam, mütləq uğursuzluğa düçar olaram. Əgər ağlıma gələn tək sənsənsə, xalqı necə düşünə bilərəm".  ,
  "Bax güllərlə dolu bağıma. Bax gözlərinə, ürəyim çiçək açır".  ,
  "İndi, sabah və əbədi olaraq yanımda olacağına söz ver."  ,
  "İtkinlik təkcə aralarındakı məsafədən deyil, həm də gerçəkləşməyən arzulardan yaranır."  ,
  "Sən heç vaxt məndən uzaq olmayacaqsan, hara getsəm, həmişə ordasan, çünki sən həmişə mənim qəlbimdəsən, yalnız bədənimiz uzaqdadır, qəlbimiz deyil".  ,
  "Hər baxışımda bilirəm ki, bizə məsafə və zaman mane olur. Amma inanıram ki, gələcəkdə mütləq bir yerdə olacağıq".  ,
  "Səni heç görmədən darıxmaq, heç vaxt oxumayacağın bir mahnı yaratmaq kimidir."  ,
  "Elə vaxtlar olur ki, məsafə həmişə mənimlə sənin aramda maneə olur, amma yenə də ürəyimdə biz həmişə yaxınıq."  ,
  “Əgər bu ürək bütün həsrəti özündə saxlaya bilmirsə, sənin üçün dua etməkdən başqa nə edim”.  ,
  "Bəlkə də bu dəqiqə ancaq bu həsrəti cilovlaya bilərəm. O vaxta qədər ki, səninlə görüşüb bu həsrəti azad edəcəm."  ,
  "Ürəyimdəki təlatümlü həsrətlə bəzən sizin sevgi dolu qucaqlarınıza ehtiyacım olur."  ,
  "Gecənin soyuğunda, daha xatırlamıram; Neçə dəfə sənin üçün darıxdığımı düşünürəm."  ,
  "Sənin üçün darıxmaq birdən yağan və uzun sürən yağış kimidir. Və yağış dayansa da, hələ də sənin üçün darıxıram."  ,
  "Sizi tanıdığımdan bəri öyrənməyə davam etmək, sizin üçün ən yaxşısı olmağı öyrənmək istəyirəm."  ,
  "Qələmlə üzünüzün fərqini bilirsinizmi? Əgər qələm yazıları silə bilərsə, üzünüzsə heç bir şey onu beynimdən silə bilməz."  ,
  "Məni narahat etməli olduğum sabah Milli İmtahan deyil, sən məni tərk edəndən sonra keçdiyim həyat imtahanıdır."  ,
  "Məktəbdəki xoşbəxtliklə bağlı məni motivasiya edən bir şey hər gün sizin təbəssümünüzü görə bilməkdir."  ,
  "Sən məktəbə getməklə evinə getmək arasındakı fərqi bilirsənmi? Məktəbə gedirsənsə, mütləq kitab və qələm gətirməlisən, amma evinə gedirsənsə, sadəcə ürəyimi və sevgimi gətirirəm".  ,
  "Sabah bazar ertəsi olsa kədərlənmirəm, səni görməsəm kədərlənirəm".  ,
  "Mənim sevgi anım sənin sevgi anına dikdir. Sevgimizi mükəmməl bir tarazlıq nöqtəsinə çevirmək."  ,
  “Finiş xəttinə çatdığınız müddətcə mən bütün dünyada qaçış yarışında iştirak etməyə hazıram”.  ,
  "Mənim ev tapşırığım sənin üçün darıxmaqdır. Riyaziyyatdan daha güclü, Fizikadan daha geniş, Biologiyadan daha güclü."  ,
  "Sənə olan sevgim ölənə qədər dayanmayacaq bir metabolizmə bənzəyir."  ,
  “Əgər jelanqkunq sənin kimidirsə, gəl məni götür, səni evə aparım”.  ,
  "Səninlə olduğu müddətcə mənim nə xoşuma gəlirsə yey, o cümlədən qara ciyər."  ,
  "Sevgi ölüm hökmü kimidir. Vurulmasan asarsan".  ,
  "Səni sevmək narkotika bənzəyir: bir dəfə aludəçi olmağa çalışsan, özünü maraqlandırmağa çalışmırsan, səni aludə etmək üçün onu tərk edirsən."  ,
  "Mən ən çox qəlyanaltı etməyi xoşlayıram, çünki qəlyanaltı ləzzətlidir. Üstəlik, siz tamamilə..."  ,
  "Bu dünya yalnız ikimizə məxsusdur. Qalan hər şey sadəcə bir müqavilədir."  ,
  "Mənim üçün bütün o günlər çərşənbə axşamıdır. Çərşənbə axşamı cənnətdə sənə yaxın olanda..."  ,
  "Bəs ikimiz də cinayətkar dəstəsi olsaq? Mən sənin ürəyini oğurladın, sən isə mənim ürəyimi."  ,
  "Sən bu səhər içdiyim qəhvə kimisən. Acı, amma asılılıq yaradır".  ,
  "Çox vaxt dodaq boyasına paxıllıq edirəm. O, səhərdən axşama kimi hər gün səni öpə bilər".  ,
  "Adını eşitmək məni axmaq kimi güldürür."  ,
  "Mən bilirəm ki, sənin sevgilin tək deyil, səni də sevən təkcə mən deyiləm."  ,
  "Sənə arzu etməyi dayandırdığımdan bəri hər şeydə həvəssiz oldum.."  ,
  "Səninlə, aşiq olmaq ən qəsdən ürək ağrısıdır."  ,
  "Sən yanımda olmadan həyatın xoşbəxtliyini hiss etmək çox çətindir."  ,
  "Ürəyimdəki təlatümlü həsrətlə bəzən sizin sevgi dolu qucaqlarınıza ehtiyacım olur."  ,
  "Sən bil ki, indiyə qədər səni hələ də sevirəm."  ,
  "Bəzən uçurtmalara paxıllıq edirəm... simlər sadəcə qırılır, hələ də onları təqib edirlər və başqaları tərəfindən ələ keçirilmək istəmirlər..."  ,
  "Səninlə nəhayət tanış olana qədər sevginin nə olduğunu bilmirdim. Amma o an ürəyim qırılmağın necə olduğunu anladım."  ,
  "Qovlamaq yorucudur, amma gözləmək daha da yorğundur\nVarlığımı fərq etməni gözləmək..."  ,
  "Sırf incidildiyinə görə sevməyi dayandırma. Çünki yağışsız göy qurşağı yoxdur, göz yaşı olmadan əsl sevgi yoxdur."  ,
  "Səni unutmaq üçün milyonlarla səbəbim var, amma heç nə məni səni sevməyi dayandırmağa məcbur edə bilməz."  ,
  "Bəzən insan sadəcə kimisə sevmək üçün özünü axmaq hiss edir."  ,
  "Sən heç vaxt peşman olmadığım ən yaxşı ürək ağrısısan."  ,
  “Gözləməyə dəyməz, sadəcə olaraq, tez-tez yalançı ümidlər verir”.  ,
  "Mənim bir hissəm ağrıyır, Onu çox yaxın, lakin toxunulmaz xatırlayıram."  ,
  "Birini sevməyin ən yaxşısı onun üçün gizli dua etməkdir."  ,
  "Kaş ki, səni itirən kimi bu hissi silə biləydim."  ,
  "Sevgi naminə özümüzü aldadırıq. Güclü olmağa çalışmaq şərəfsizliyə çevrilir".  ,
  "Məni öz evin kimi düşün, getsən evə hara gedəcəyini anlayırsan. İstəsən qal, darıxsan get..."  ,
  "Mən qarışmışam, məyus olmalıyam, ya yox? Məyus olsam, mən onun üçün kiməm?\n\nÜzülmədimsə, amma onun sözlərini gözləyirəm".  ,
  "Mənim həsrətim ayaqda qalan bir budaq kimidir. Onu müşayiət edəcək yarpaq qalmasa da, nəhayət quruyub, qırılıb ölənə qədər."  ,
  "Düşünürəm ki, biz indi eyni xatirələrə sahib iki yad insanıq."  ,
  "Bir neçə dəqiqə də olsa sənə nifrət et ki, səni unutmaq çox çətin olmasın."  ,
  "Mən səni bütün qəlbimlə sevirəm, amma sən hisslərini başqa insanlarla bölüşürsən."  ,
  "Səni sevmək məni sındıra bilər, amma nədənsə səndən ayrılmaq məni düzəldə bilməz."  ,
  "Sən mənim həyatımda birincisən. Amma mən səndən sonra ikinciyəm."  ,
  "Yalnız yuxuda görüşə bilsək, əbədi yatmaq istəyirəm."  ,
  "Səni xoşbəxt görmək mənim xoşbəxtliyimdir, baxmayaraq ki, sən mənsiz xoşbəxtsən."  ,
  "Bəzən bir obyektə həsəd aparıram. Onun dadı yoxdur, amma həmişə ehtiyac var. Məndən fərqli olaraq, zövqü olan, lakin tərk edilmiş və diqqətdən kənarda qalan..."  ,
  "Mən necə hərəkət edə bilərəm ki, ürəyim yalnız sən dincəlsin?"  ,
  "Səninlə bağlı xatirələr mənim üçün ev kimidir. Odur ki, ağlım nə vaxt gəzirsə, o həmişə sənə qayıdacaq."  ,
  "Toxuma niyə faydalıdır? Çünki sevgi heç vaxt quruyub getmir. - Sujiwo Tejo"  ,
  "Əgər səni sevmək səhvdirsə, yaxşı ki, səhv etməyə davam edim."  ,
  "Səninlə tanış olandan bəri öyrənməyə davam etmək istəyirəm. Sizin üçün ən yaxşısı olmağı öyrənin."  ,
  "Bəzi insanlar sırf güldüyünü görmək üçün axmaqlıq edərlər. Və buna sevinirlər."  ,
  "Mən yaxşı insan deyiləm, amma sizin üçün ən yaxşısı olmağı öyrənəcəyəm."  ,
  “Biz ölmürük, amma bizi əvvəlki kimi yeriyə bilməyən yaralarımızdır”.  ,
  "Sizin varlığınız hər səhər ehtiyacım olan bir fincan qəhvə kimidir və bu, məni gün üçün həyəcanlı qalmağa təşviq edə bilər."  ,
  "Mən həqiqətən dünyanı sənə vermək istəyirəm. Amma bu mümkün olmadığına görə, o zaman sənə həyatımdakı ən vacib şeyi, mənim dünyam olanı verəcəyəm."  ,
  “Romantik görünməkdənsə, sonluğu faciəvi şəkildə bitməkdənsə, zarafatlı, lakin şirin oxumaq daha yaxşıdır”.  ,
  "Ben məyusluqla nəticələnmir, nə vaxt ümid edəcəyinizi və nə vaxt dayanacağınızı bilməlisiniz."  ,
  "Mən, Ki wong Jowo, "I Love U" sözünün mənasını anlamıram. Amma "Mən sənin heyətini sevirəm" sözünün mənasını başa düşürəm".  ,
  "Sənin gözəl və sugihinə ehtiyac yoxdur, əminəm ki, Wes xoşbəxt və dəlidir."  ,
  "Heyətinizə olan sevgim kamera tərəfindən parçalandı, ekipajınıza diqqət hələ də bulanıqdır."  ,
  "Saben dino xəyal qurmağa tənbəldir, amma axmaq ola bilməz."  ,
  "30 dino ilə görüşməyin, özümü bir ay kimi hiss edirəm."  ,
  "Mən rezin itirmiş pişik kimi sənsizəm. Əbyar."  ,
  "Mən bunu istəyirəm, mən o vaxt oynayıram. Supoyo mən iso nemokne kowe lewih hot. Mən sizin slira ilə kanggo urip olanda Ben Lewih dowo."  ,
  "Mən heç vaxt kui tresno, kajaba sak çılpaq sənin slira ilə görüşmək nə olduğunu bilmədim."  ,
  "Love aa ka neng moal leungit-leungit sanajan aa geus marry deui."  ,
  "Səbrin məhduddur, amma sevgin, ka anjeun henteu aya se epna."  ,
  "Bayclean istifadə etsəniz, pis olacaq."  ,
  "A işin gücun yoxdu senin ? Random atır hələ burda."  ,
  "Mən həmişə tək nəfəs alacağam, özümə kömək etmək çox vaxt aparacaq."  ,
  "Nyaahna, çay lazımdır və bank işçisi hələ də borc yığır (hayoh mumuntil)."  ,
  "Uranqın səbrinin həddi var, amma urana olan sevgin sənin üçün yaxşıdır."  ,
  "Hayang Məncə bu dünyada filan sevgi sözlərini söyürəm, o zaman mən pisəm, bir yerə yığmaq istəmirəm ki, Anjeun sənə böyük sevgi bəsləsin, Anjeun."  ,
  "Sevmiyin A kişi Bağlanmıyın kimese ."  ,
  "Abdi sanes jalmi nu mükəmməl pikeun anjeun, sareng sanes oge nu ən yaxşı kanggo anjeun. Amma nu, şübhəsiz ki, abdi jalmi hiji-hijina nu sevimli anjeun olmağa davam edir."  ,
  "Sadəcə şəbəkəni itirmək kifayətdir, sən yox."  ,
  "Məni tez-tez ciyər yeməyə məcbur edirlər. Amma hələ də burada olduğunu bilmək məni yenidən xoşbəxt edir."  ,
  "Mənim düşmənlərim sənə sahib olmaq istəyənlərdir."  ,
  "Çoxları həmişə oradadır, amma mənim istədiyim tək sənsənsə, onda necə?"  ,
  "Mənim yuxu saatlarımı həsrət pozur."  ,
  “Bəsdir ki, Çin uzaqdadır, bizi sevmə”.  ,
  "Əsas olan sənin xoşbəxtliyindir, mən önəmli deyiləm.."  ,
  "Mənim tək arzum sənin tərəfindən sevilməkdir."  ,
  "Sənsiz mən wiuw wiuw wiuw olmayan təcili yardım maşını kimiyəm."  ,
  "Antarktidanın uzaqda olması kifayətdir. Antarktida deyil."
]
